### ISSUE TITLE
ISSUE #1

### ISSUE THREAD

**Issue by cryptoknightsz** [khondokerXhasan/Tomarket-BOT#1]
![image](https://github.com/user-attachments/assets/55c9bfd3-182c-4e97-9310-18086f7439c4)

**Comment by cryptoknightsz** [comment]
There's 2 error, 1st one is wallet and 2nd one while processing task

**Comment by khondokerXhasan** [comment]
@cryptoknightsz wallet problem fixed, update it.

**Comment by khondokerXhasan** [comment]
@cryptoknightsz if you again face any error plz tell me

**Comment by cryptoknightsz** [comment]
Sure, let me check

**Comment by cryptoknightsz** [comment]
![image](https://github.com/user-attachments/assets/b3e2f2c9-fbbe-403e-b0e1-8b455b2522bb)
One more error, happens with every session

**Comment by khondokerXhasan** [comment]
@cryptoknightsz check new update

**Comment by cryptoknightsz** [comment]
![image](https://github.com/user-attachments/assets/c5ba3b0e-15e0-4f97-96ff-f2ef8db937f9)
It's stuck here, tried like 10-12 times

**Comment by khondokerXhasan** [comment]
Plz dm in telegram https://t.me/scripts_hub_chat

**Comment by cryptoknightsz** [comment]
![image](https://github.com/user-attachments/assets/5bb1218c-dd8a-4389-976f-45a80e63e176)
Another issue
