### ISSUE TITLE
PROXY

### ISSUE THREAD

**Issue by Ollykid** [khondokerXhasan/Tomarket-BOT#4]
it keeps writing proxy errors but ur script is dope because of that I can't use it am ganna go look for a new source

**Comment by khondokerXhasan** [comment]
@Ollykid which problem you are facing, tell me i will try to solve it.

**Comment by Ollykid** [comment]
> @Ollykid which problem you are facing, tell me i will try to solve it.

Proxy is not working bro 🥲🥲🥲

**Comment by khondokerXhasan** [comment]
@Ollykid show me the error ?
