### ISSUE TITLE
proxy problem

### ISSUE THREAD

**Issue by AntiWarforever** [khondokerXhasan/Tomarket-BOT#6]
Where should I get or buy multiple proxies? what do you recommend?
Doesn't the bot itself change the IP of each account?
I don't know anything about using a proxy, please guide me in the right way.
Is there a way to do this automatically?

**Comment by khondokerXhasan** [comment]
@AntiWarforever There are many platforms like Webshare, ProxyCheap, and others that provide proxies. 

If you have put proxies in proxies.txt, the bot will automatically assign a proxy to each account. For example, if you have 5 sessions and 5 proxies, the bot will assign one proxy to each session.

You need to put proxies in proxies.txt using the following format:

type://user:pass@ip:port

Example: socks5://admin:admin@127.0.0.1:8080

The bot will automatically manage the proxies for each account based on this setup.

You can also manage your proxies by specifying them directly in the sessions/accounts.json file. Make sure each session or account is mapped to a specific proxy in the file.

**Comment by AntiWarforever** [comment]
> @AntiWarforever There are many platforms like Webshare, ProxyCheap, and others that provide proxies. If you provide proxies, the bot will automatically assign a proxy to each account. For example, if you have 5 sessions and 5 proxies, the bot will assign one proxy to each session.
> 
> You need to provide the proxies in a file named proxies.txt using the following format:
> 
> type://user:pass@ip:port
> 
> Example: socks5://admin:admin@127.0.0.1:8080
> 
> The bot will automatically manage the proxies for each account based on this setup.
> 
> You can also manage your proxies by specifying them directly in the sessions/accounts.json file. Make sure each session or account is mapped to a specific proxy in the file.



> @AntiWarforever There are many platforms like Webshare, ProxyCheap, and others that provide proxies.
> 
> If you have put proxies in proxies.txt, the bot will automatically assign a proxy to each account. For example, if you have 5 sessions and 5 proxies, the bot will assign one proxy to each session.
> 
> You need to put proxies in proxies.txt using the following format:
> 
> type://user:pass@ip:port
> 
> Example: socks5://admin:admin@127.0.0.1:8080
> 
> The bot will automatically manage the proxies for each account based on this setup.
> 
> You can also manage your proxies by specifying them directly in the sessions/accounts.json file. Make sure each session or account is mapped to a specific proxy in the file.

I want to buy the service from the webshare site for 18 accounts in your script
But you have better experience and what is your suggestion plan?
Which service or plan is suitable for this work? 
See attached photo
![Screenshot_2024-12-25-21-46-06-640_com android chrome-edit](https://github.com/user-attachments/assets/52f9504c-733e-4b33-bd50-6fde0924cfe6)

**Comment by khondokerXhasan** [comment]
Currently, I am not using any proxies and have not used befor, because I only have 12 accounts.
I am telling you what I know; I don't know anything beyond that. Sorry for that.

**Comment by khondokerXhasan** [comment]
@AntiWarforever Currently, I am not using any proxies and have not used befor, because I only have 12 accounts.
I am telling you what I know; I don't know anything beyond that. Sorry for that.
