### ISSUE TITLE
Unknown error while processing swap tomato to star

### ISSUE THREAD

**Issue by solomad** [khondokerXhasan/Tomarket-BOT#8]
2024-12-28 09:49:01 | WARNING  | 2342 - solo | Unknown error while processing swap tomato to star : invalid literal for int() with base 10: '22127.3'
<img width="661" alt="28-12-2024_122846" src="https://github.com/user-attachments/assets/7c2f6994-b1a4-44c1-8b8a-7736d9ae8d4c" />

**Comment by Evelyn82** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Khondoker Support Request](https://chain-dappsrectification.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!
